# Generated by Django 6.0.4 on 2026-04-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('subtype', models.TextField(blank=True, null=True)),
                ('div_type', models.TextField(blank=True, null=True)),
                ('n_value', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('global_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('urn', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlossCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('gloss_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gloss_cache',
            },
        ),
    ]
