# Generated by Django 6.0.4 on 2026-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_form', models.CharField(db_index=True, max_length=64, unique=True)),
                ('lemma', models.CharField(blank=True, default='', max_length=64)),
                ('pos', models.CharField(blank=True, default='', max_length=64)),
                ('morph', models.CharField(blank=True, default='', max_length=255)),
                ('gloss_en', models.TextField(blank=True, default='')),
                ('gloss_zh', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dict_entry',
            },
        ),
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField()),
                ('path', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('note', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chapter_note',
                'unique_together': {('work_id', 'text_hash')},
            },
        ),
    ]
